### ISSUE TITLE
Other timeseries data source

### ISSUE THREAD

**Issue by robchallen** [emmadoughty/Daily_COVID-19#3]
I'm maintaining timeseries data also: Am cross referencing your site and pulling data from PHE:

https://docs.google.com/spreadsheets/d/1snb-vYuH7fVpTuyoQrM8zWiABYoXbSrnn44w-zlhM90/edit?usp=sharing

Feel free to borrow / steal

```{r}
UK = list(
  regional=read.csv(file="https://docs.google.com/spreadsheets/d/e/2PACX-1vQod-HdDk4Nl8BFcunG5P-QA2CuKdIXCfK53HJDxcsaYlOov4FFc-yQciJyQFrqX5_n_ixz56S7uNBh/pub?gid=163112336&single=true&output=csv"),
  englandNHS=read.csv(file="https://docs.google.com/spreadsheets/d/e/2PACX-1vQod-HdDk4Nl8BFcunG5P-QA2CuKdIXCfK53HJDxcsaYlOov4FFc-yQciJyQFrqX5_n_ixz56S7uNBh/pub?gid=0&single=true&output=csv"),
  englandLA=read.csv(file="https://docs.google.com/spreadsheets/d/e/2PACX-1vQod-HdDk4Nl8BFcunG5P-QA2CuKdIXCfK53HJDxcsaYlOov4FFc-yQciJyQFrqX5_n_ixz56S7uNBh/pub?gid=796246456&single=true&output=csv")
)
```

Will get you the data in R. Finding lots of data quality issues - cumulative counts decreasing for example.

**Comment by petelaud** [comment]
@robchallen 
I've put together a lookup table to group local authorities to regions, which can be used to produce region totals from UA totals:
https://docs.google.com/spreadsheets/d/1b06Z3z5oIyKIiMDl-eWhXojrhXTzygNGd2SkUZOs8sg/edit?usp=sharing

From source data found here:
https://geoportal.statistics.gov.uk/datasets/register-of-geographic-codes-december-2019-for-the-united-kingdom (Drop-down menu: Lookups > Administrative lookups > Wards to LAD to counties etc)

**Comment by robchallen** [comment]
@PeteLaud Thanks. have stolen. Do you have demographics for UA region? 
Ideally UA, age ranges and geographic area and population density. 
ping me your email on rob@terminological.co.uk and I will give you write access to the Google sheet.

**Comment by emmadoughty** [comment]
@robchallen Do you still need demographics data? I've got my hands on 2017 age and gender breakdowns for most geographic areas where case data is available and am in the process of trying to put it into a useful format- hopefully can get it done today

**Comment by emmadoughty** [comment]
@robchallen NB I found 2018 data in a better format and just uploaded in Data directory

**Comment by robchallen** [comment]
I found some already
Thanks though.

Dr. Robert Challen
terminological <http://www.terminological.co.uk>
mobile: 07968 566 335
skype: rjchallen
linkedin: https://uk.linkedin.com/in/robchallen
