### ISSUE TITLE
Doubling time

### ISSUE THREAD

**Issue by petelaud** [emmadoughty/Daily_COVID-19#5]
Any thoughts on the government's assumption of a 5-day doubling time? 
 @robchallen? 
(https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf)

**Comment by emmadoughty** [comment]
I don't feel that this is something I can comment on at this time. I'm sorry!
