### ISSUE TITLE
Data for 17th March and for Scotland, Wales and Northern Ireland

### ISSUE THREAD

**Issue by geeogi** [emmadoughty/Daily_COVID-19#6]
Thanks for recording this data from PHE. We have been using it to power [our site](https://www.covidlive.co.uk/). 

I'd like to know if this dataset is being maintained and in what capacity? I notice that the data for March 17th (by UTLA) is not yet added. I also notice that yesterday the values for Wales, Scotland and Northern Ireland were included, but they've since gone. I'm happy to assist with the data collection if I can be helpful.

**Comment by emmadoughty** [comment]
I have some data quality concerns about the data coming from PHE. For the time being, I will, therefore, be maintaining only the COVID_cum.csv file for geographic breakdowns. This contains the raw data from PHE about the number of total cases on the dates specified. You will see that in some areas the number of cases decreases from one day to the next. It is unclear why this is.
