### ISSUE TITLE
Consistent date formats + citation

### ISSUE THREAD

**Issue by jhellewell14** [emmadoughty/Daily_COVID-19#7]
Hello, 

Thank you so much for collating this data! We are hoping to use it to produce estimates of the time-varying reproduction number at the regional level (we are currently doing this at the [country level](https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html) and [regional level for Italy](https://cmmid.github.io/topics/covid19/current-patterns-transmission/italy-time-varying-transmission.html)).

1. We'd like to add you as an author to the work we produce to recognise the work you are putting in doing this. Let me know name and institution if you would like to be added as an author. 
2. Can you keep the date format consistent in the csv files please, saves me a bit of a headache trying to re-format the dates later!

Thanks,
Joel

**Comment by emmadoughty** [comment]
Hi Joel, 

These analyses look fantastic. If there's anything I can do to help out,  let me know.

1. It's very considerate to include me as an author on your paper. I think I've found your email and will send you my details in that way.

2. No problem and sorry for the headache!

Note, there seems to be some potential quality issues with the official data at geographic breakdown level coming from PHE/Scottish gov website. I would encourage you to use the COVID_cum.csv data which collates the total number of cases announced per area per day. You'll see that the total number of cases decreases from one day to the next in some local areas which makes no sense (look at Sheffield for an extreme example). 

Best wishes, 

Emma

**Comment by emmadoughty** [comment]
Thanks, Rob!

**Comment by jhellewell14** [comment]
Great! My email is Joel.Hellewell@lshtm.ac.uk (in case you found a different one) so just send me a message.

Cheers,
Joel
